{{- define "common.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
{{ template "common.metadata" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $name := .Values.imagePullSecrets }}
      - name: {{ $name -}}
        {{- end }}
      {{- end }}
      containers:
      -
{{ include "common.container.tpl" . | indent 8 }}
{{- end -}}
{{- define "common.deployment" -}}
{{- template "common.util.merge" (append . "common.deployment.tpl") -}}
{{- end -}}
