{{- define "common.ingressroute.tpl" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
{{ template "common.metadata" . }}
  {{- if .Values.ingressroute.spec }}
  {{- $tpl := toYaml .Values.ingressroute.spec }}
spec: {{ tpl $tpl . | nindent 2 }}
  {{- end }}
{{- end -}}

{{- define "common.ingressroute.metadata" -}}
{{- end -}}

{{- define "common.ingressroute" -}}
{{- template "common.util.merge" (append . "common.ingressroute.tpl") -}}
{{- end -}}