{{- define "common.ingressroute.tpl" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
{{ template "common.metadata" . }}
spec: {}
{{- end -}}

{{- define "common.ingressroute" -}}
{{- template "common.util.merge" (append . "common.ingressroute.tpl") -}}
{{- end -}}